export interface SlideImage {
  filename: string;
  alt: string;
}

export const slideRows: SlideImage[][] = [
  // Row 1 (left scroll)
  [
    { filename: "000-01-a-cover.webp", alt: "Cover slide" },
    { filename: "001-01-b-cover-image-right.webp", alt: "Cover image right slide" },
    { filename: "002-01-c-cover-minimal.webp", alt: "Cover minimal slide" },
    { filename: "003-01-d-cover-typography.webp", alt: "Cover typography slide" },
    { filename: "004-01-e-cover-creative.webp", alt: "Cover creative slide" },
    { filename: "005-01-f-cover-artistic.webp", alt: "Cover artistic slide" },
    { filename: "006-02-about.webp", alt: "About slide" },
    { filename: "007-02-b-section-left-aligned.webp", alt: "Section left aligned slide" },
    { filename: "008-02-c-section-number.webp", alt: "Section number slide" },
    { filename: "009-02-d-section-dark.webp", alt: "Section dark slide" },
    { filename: "010-02-e-section-split.webp", alt: "Section split slide" },
    { filename: "011-02-f-section-minimal.webp", alt: "Section minimal slide" },
    { filename: "012-03-features.webp", alt: "Features slide" },
    { filename: "013-03-speaker.webp", alt: "Speaker slide" },
    { filename: "014-04-code-example.webp", alt: "Code example slide" },
  ],
  // Row 2 (right scroll)
  [
    { filename: "015-05-charts.webp", alt: "Charts slide" },
    { filename: "016-06-layout.webp", alt: "Layout slide" },
    { filename: "017-07-table.webp", alt: "Table slide" },
    { filename: "018-08-icons.webp", alt: "Icons slide" },
    { filename: "019-09-line-chart.webp", alt: "Line chart slide" },
    { filename: "020-10-pie-chart.webp", alt: "Pie chart slide" },
    { filename: "021-11-area-chart.webp", alt: "Area chart slide" },
    { filename: "022-12-blockquote.webp", alt: "Blockquote slide" },
    { filename: "023-13-math.webp", alt: "Math slide" },
    { filename: "024-14-shapes.webp", alt: "Shapes slide" },
    { filename: "025-15-three-columns.webp", alt: "Three columns slide" },
    { filename: "026-16-ordered-nested-list.webp", alt: "Ordered nested list slide" },
    { filename: "027-17-custom-background.webp", alt: "Custom background slide" },
    { filename: "028-18-mixed-columns.webp", alt: "Mixed columns slide" },
    { filename: "029-19-code-explanation.webp", alt: "Code explanation slide" },
  ],
  // Row 3 (left scroll)
  [
    { filename: "030-20-icons-with-labels.webp", alt: "Icons with labels slide" },
    { filename: "031-21-section-typography.webp", alt: "Section typography slide" },
    { filename: "032-22-inline-code-links.webp", alt: "Inline code links slide" },
    { filename: "033-23-dashboard.webp", alt: "Dashboard slide" },
    { filename: "034-24-custom-width-columns.webp", alt: "Custom width columns slide" },
    { filename: "035-25-multi-language-code.webp", alt: "Multi language code slide" },
    { filename: "036-26-shapes-decorative.webp", alt: "Shapes decorative slide" },
    { filename: "037-27-kpi-cards.webp", alt: "KPI cards slide" },
    { filename: "038-28-comparison-table.webp", alt: "Comparison table slide" },
    { filename: "039-29-dark-gradient.webp", alt: "Dark gradient slide" },
    { filename: "040-30-b-image-bottom-caption.webp", alt: "Image bottom caption slide" },
    { filename: "041-30-c-image-left-caption.webp", alt: "Image left caption slide" },
    { filename: "042-30-d-image-right-caption.webp", alt: "Image right caption slide" },
    { filename: "043-30-e-image-comparison.webp", alt: "Image comparison slide" },
    { filename: "044-30-f-image-overlay-text.webp", alt: "Image overlay text slide" },
  ],
  // Row 4 (right scroll)
  [
    { filename: "045-30-g-image-card-list.webp", alt: "Image card list slide" },
    { filename: "046-30-h-three-image-flow.webp", alt: "Three image flow slide" },
    { filename: "047-30-i-heading-image-subheading.webp", alt: "Heading image subheading slide" },
    { filename: "048-30-image-with-caption.webp", alt: "Image with caption slide" },
    { filename: "049-30-j-three-images-caption.webp", alt: "Three images caption slide" },
    { filename: "050-31-card-grid.webp", alt: "Card grid slide" },
    { filename: "051-32-image-left-text-right.webp", alt: "Image left text right slide" },
    { filename: "052-33-text-left-image-right.webp", alt: "Text left image right slide" },
    { filename: "053-34-centered-heading.webp", alt: "Centered heading slide" },
    { filename: "054-35-big-number.webp", alt: "Big number slide" },
    { filename: "055-36-team-profiles.webp", alt: "Team profiles slide" },
    { filename: "056-37-timeline.webp", alt: "Timeline slide" },
    { filename: "057-38-checklist.webp", alt: "Checklist slide" },
    { filename: "058-39-before-after.webp", alt: "Before after slide" },
  ],
  // Row 5 (left scroll)
  [
    { filename: "059-40-gradient-cards.webp", alt: "Gradient cards slide" },
    { filename: "060-41-numbered-steps.webp", alt: "Numbered steps slide" },
    { filename: "061-42-hero-centered.webp", alt: "Hero centered slide" },
    { filename: "062-43-image-full-with-text.webp", alt: "Image full with text slide" },
    { filename: "063-44-two-row-cards.webp", alt: "Two row cards slide" },
    { filename: "064-45-quote-card.webp", alt: "Quote card slide" },
    { filename: "065-46-icon-list-horizontal.webp", alt: "Icon list horizontal slide" },
    { filename: "066-47-centered-section.webp", alt: "Centered section slide" },
    { filename: "067-48-split-dark-light.webp", alt: "Split dark light slide" },
    { filename: "068-49-qa-contact.webp", alt: "QA contact slide" },
    { filename: "069-50-kpi-strip.webp", alt: "KPI strip slide" },
    { filename: "070-51-funnel.webp", alt: "Funnel slide" },
    { filename: "071-52-b-three-column-text.webp", alt: "Three column text slide" },
    { filename: "072-52-c-two-column-image-text.webp", alt: "Two column image text slide" },
  ],
  // Row 6 (right scroll)
  [
    { filename: "073-52-d-three-column-image-text.webp", alt: "Three column image text slide" },
    { filename: "074-52-two-column-text.webp", alt: "Two column text slide" },
    { filename: "075-53-stacked-images.webp", alt: "Stacked images slide" },
    { filename: "076-54-screenshot-callouts.webp", alt: "Screenshot callouts slide" },
    { filename: "077-55-logo-wall.webp", alt: "Logo wall slide" },
    { filename: "078-56-timeline.webp", alt: "Timeline slide" },
    { filename: "079-57-big-number.webp", alt: "Big number slide" },
    { filename: "080-58-do-dont.webp", alt: "Do dont slide" },
    { filename: "081-59-pricing-table.webp", alt: "Pricing table slide" },
    { filename: "082-61-team-grid.webp", alt: "Team grid slide" },
    { filename: "083-62-swot-matrix.webp", alt: "SWOT matrix slide" },
    { filename: "084-63-pyramid.webp", alt: "Pyramid slide" },
    { filename: "085-64-concentric-circles.webp", alt: "Concentric circles slide" },
    { filename: "086-65-venn-diagram.webp", alt: "Venn diagram slide" },
  ],
  // Row 7 (left scroll)
  [
    { filename: "087-66-cycle-diagram.webp", alt: "Cycle diagram slide" },
    { filename: "088-67-hub-spoke.webp", alt: "Hub spoke slide" },
    { filename: "089-68-stair-chart.webp", alt: "Stair chart slide" },
    { filename: "090-69-iceberg.webp", alt: "Iceberg slide" },
    { filename: "091-70-3x3-matrix.webp", alt: "3x3 matrix slide" },
    { filename: "092-71-layer-stack.webp", alt: "Layer stack slide" },
    { filename: "093-72-value-chain.webp", alt: "Value chain slide" },
    { filename: "094-73-gauge-meter.webp", alt: "Gauge meter slide" },
    { filename: "095-74-flowchart-decision.webp", alt: "Flowchart decision slide" },
    { filename: "096-75-agenda.webp", alt: "Agenda slide" },
    { filename: "097-75-b-video-with-description.webp", alt: "Video with description slide" },
    { filename: "098-75-video-embed.webp", alt: "Video embed slide" },
    { filename: "099-76-agenda.webp", alt: "Agenda slide" },
    { filename: "100-76-b-agenda-grid.webp", alt: "Agenda grid slide" },
  ],
  // Row 8 (right scroll)
  [
    { filename: "101-76-c-agenda-highlight.webp", alt: "Agenda highlight slide" },
    { filename: "102-76-comparison-cards.webp", alt: "Comparison cards slide" },
    { filename: "103-76-d-agenda-grid-3day.webp", alt: "Agenda grid 3-day slide" },
    { filename: "104-77-feature-comparison.webp", alt: "Feature comparison slide" },
    { filename: "105-77-stat-grid.webp", alt: "Stat grid slide" },
    { filename: "106-78-faq.webp", alt: "FAQ slide" },
    { filename: "107-78-process-flow.webp", alt: "Process flow slide" },
    { filename: "108-79-testimonial-wall.webp", alt: "Testimonial wall slide" },
    { filename: "109-80-feature-spotlight.webp", alt: "Feature spotlight slide" },
    { filename: "110-81-pros-cons.webp", alt: "Pros cons slide" },
    { filename: "111-82-data-narrative.webp", alt: "Data narrative slide" },
    { filename: "112-83-risk-matrix.webp", alt: "Risk matrix slide" },
    { filename: "113-84-tech-stack.webp", alt: "Tech stack slide" },
    { filename: "114-99-thank-you.webp", alt: "Thank you slide" },
  ],
];
